apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: rabbitmq-training-portal
spec:
  portal:
    registration:
      type: anonymous
  workshops:
  - name: rabbitmq-eduk8s-workshop
    capacity: 1
    expires: 60m
    orphaned: 5m
