apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: rabbitmq-eduk8s-workshop
spec:
  title: RabbitMQ Workshop
  description: Operator Workshop for installing, monitoring and operating RabbitMQ
  vendor: tanzu.vmware.com
  difficulty: beginner
  duration: 15m
  url: https://github.com/wlund-pivotal/rabbitmq-workshop
  content:
    image: wxlund/jdk11:latest
    files: github.com/wlund-pivotal/rabbitmq-workshop
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
